# The URL the site will be built for
base_url = "https://blog.tfei.moe"
title = "有希書簡"
default_language = "zh-tw"
generate_feed = true
theme = "Seje2"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
# show Chinese date format instead of normal date format
seje_chinese_date = true
# show summary instead of the whole article on the index page
seje_show_summary_only = false
# Google Font API mirror URLs (for China mainland users, try fonts.loli.net)
seje_font_mirror = "fonts.googleapis.com"
# whether use traditional Chinese style vertical layout
seje_vertical_layout = true
# additional custom fonts to include (must be in CSS font-family format)
seje_custom_fonts = ""
# whether enable darkmode. Possible values: auto, always, never
seje_darkmode = "auto"
# Your site blog links
seje_menu_links = [
    {url = "$BASE_URL/", name = "home"},
    {url = "$BASE_URL/archives", name = "archives"},
    {url = "$BASE_URL/about",  name = "about"},
    {url = "$BASE_URL/friends",  name = "friends"},
    {url = "$BASE_URL/assertions",  name = "assertions"},
    {url = "$BASE_URL/atom.xml", name = "rss"},
]

[languages.zh-tw.translations]
title = "有希書簡"
home = "主頁"
archives = "歸檔"
about = "關於"
friends = "朋友"
assertions = "斷言"
rss = "訂閱"
more = "查看全文"
olderArticle = "舊文"
newer = "上一篇"
older = "下一篇"
loading = "加載中..."